PaymentSystem/PaymentSystem/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.Services;
using DAO.Model;
using DAO.Repository;
using Microsoft.AspNet.Identity;

namespace PaymentSystem.Controllers
{
    public class CardController : Controller
    {
        private readonly IRepositoryFactory _factory;

        public CardController(IRepositoryFactory factory)
        {
            _factory = factory;
        }

        // GET: Card
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Card card)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CardService.CreateCard(card, User.Identity.GetUserId(), _factory);
                    TempData["SuccessMessage"] = "Карта успешно добавлена";
                    return RedirectToAction("Index", "Home");
                }
                catch (ValidationException e)
                {
                    ModelState.AddModelError(e.Property,e.Message);
                }
            }
            return View(card);
        }

        public ActionResult Details(long id = 0)
        {
            var account = AccountService.GetAccount(_factory, id, User.Identity.GetUserId(), User.IsInRole("User"));
            if(account==null)
                return new HttpNotFoundResult();
            return View(account);
        }

        public ActionResult BlockedAccounts()
        {
            return View();
        }

        public ActionResult Block(long id = 0)
        {
            try
            {
                AccountService.BlockAccount(_factory, id, User.Identity.GetUserId(), User.IsInRole("User"));
                return Content("Счет успешно заблокирован");
            }
            catch (ValidationException e)
            {
                return new HttpNotFoundResult(e.Message);
            }
            
        }

        public ActionResult RequertToUnBlock(long id = 0)
        {
            try
            {
                RequestService.AddRequest(id, User.Identity.GetUserId(), _factory);
                return Content("Запрос отправлен администратору на разблокировку.");
            }
            catch (ValidationException e)
            {
                return new HttpNotFoundResult(e.Message);
            }
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(long id = 0)
        {
            AccountService.UnBlockAccount(_factory, id);
            return Content("Аккаунт разблокирован.");
        }
    }
}

PaymentSystem/PaymentSystem/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaymentSystem.Models;

namespace PaymentSystem.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public PartialViewResult Index()
        {
            MenuItemViewModel[] items;
            if (User.IsInRole("Admin"))
            {
                items = new[]
                {
                    new MenuItemViewModel("Главная", Url.Action("Index", new {Controller = "Home", area = ""}),
                        "fa-home"),
                    new MenuItemViewModel("Пользователи", "", "fa-users",
                        new MenuItemViewModel("Все пользователи",
                            Url.Action("AllUsers", new {Controller = "Account", area = ""}), ""),
                        new MenuItemViewModel("Заблокированные",
                            Url.Action("AllBlockedUsers", new {Controller = "Account", area = ""}), "")
                        ),
                    new MenuItemViewModel("Заблокированные счета",
                        Url.Action("BlockedAccounts", new {Controller = "Card", area = ""}), "fa-ban"),
                    new MenuItemViewModel("Отчеты","","fa-area-chart",
                            new MenuItemViewModel("Большие операции",
                                Url.Action("Index", new {Controller = "Report", area = ""}),"")
                        ),
                };
            }
            else if (User.IsInRole("Support"))
            {
                items = new[]
                {
                    new MenuItemViewModel("Главная", Url.Action("Index", new {Controller = "Home", area = ""}),
                        "fa-home"),
                    new MenuItemViewModel("Входящие сообщения",
                        Url.Action("Inbox", new {Controller = "Message", area = ""}), ""),
                    new MenuItemViewModel("Исходящие сообщения",
                        Url.Action("Outbox", new {Controller = "Message", area = ""}), ""),
                };
            }
            else
            {
                items = new[]
                {
                    new MenuItemViewModel("Главная", Url.Action("Index", new {Controller = "Home", area = ""}),
                        "fa-home"),
                    new MenuItemViewModel("Операции", "", "fa-dashboard",
                        new MenuItemViewModel("Пополнить счет",
                            Url.Action("CreateReplenishment", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("Банковский платеж",
                            Url.Action("CreateBankOperation", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("С карты на карту",
                            Url.Action("CreateCardOperation", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("Платеж на мобильный",
                            Url.Action("CreateMobileOperation", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("Подготовить платеж",
                            Url.Action("CreatePreparedPayment", new {Controller = "Operation", area = ""}), "")
                        ),
                    new MenuItemViewModel("Мои счета", "", "fa-credit-card",
                        new MenuItemViewModel("Все карты", Url.Action("Index", new {Controller = "Card", area = ""}), ""),
                        new MenuItemViewModel("Добавить карту",
                            Url.Action("Create", new {Controller = "Card", area = ""}), "")
                        ),
                    new MenuItemViewModel("История операций", "", "fa-history",
                        new MenuItemViewModel("Все операции",
                            Url.Action("Index", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("Пополнения",
                            Url.Action("Replenishments", new {Controller = "Operation", area = ""}), ""),
                        new MenuItemViewModel("Платежи",
                            Url.Action("Payments", new {Controller = "Operation", area = ""}), "")
                        ),
                    new MenuItemViewModel("Помощь", "", "fa-envelope",
                        new MenuItemViewModel("Входящие сообщения",
                            Url.Action("Inbox", new {Controller = "Message", area = ""}), ""),
                        new MenuItemViewModel("Исходящие сообщения",
                            Url.Action("Outbox", new {Controller = "Message", area = ""}), ""),
                        new MenuItemViewModel("Новое сообщение",
                            Url.Action("NewMessage", new {Controller = "Message", area = ""}), "")
                        ),                        
                };
            }
            return PartialView("_Menu", items);
        }
    }
}

PaymentSystem/PaymentSystem/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.Services;
using DAO.Repository;

namespace PaymentSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RequestController : Controller
    {
        private readonly IRepositoryFactory _factory;

        public RequestController(IRepositoryFactory factory)
        {
            _factory = factory;
        }

        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Last()
        {
            ViewBag.Count = RequestService.CountRequest(_factory);
            return PartialView(RequestService.FirstNRequests(_factory, 5));
        }
    }
}

PaymentSystem/PaymentSystem/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Страница не найдена</title>
    <meta name="robots" content="noindex" />
    <style type="text/css">
			
			body{margin: 0px;overflow: hidden; font-family: 'Roboto', sans-serif;}
			#video{width: 100%; height: 100%; margin-top: -100px;}
			.videobg{position: relative;}
			.pattern{position: absolute; width: 100%; height: 100%; top: 0;left: 0; background: #272822; opacity: 0.4;}
			.wrapper{width: 800px; margin: 300px auto auto auto; position: absolute; top: 0;left: 0;right: 0;bottom: 0;}
			.wrapper h1{text-align: center; color: white; font-weight: 100; font-size: 60px;text-transform: uppercase;}
			.wrapper p{color: white; text-align: center; font-weight: 100; font-size: 20px; padding-bottom: 20px;}
			.wrapper a{padding: 10px; border: 1px solid white; border-radius: 5px; color: white; font-weight: 100; text-align: center; margin-top: 40px; text-decoration: none; transition: 0.2s;}
			.wrapper a:hover{background: white; color: black; text-decoration: none; transition: 0.2s;}
    </style>
</head>
<body>
    <div class="videobg">
        <div class="pattern"></div>
        <video autoplay loop muted id="video">
            <source src="~/videobg/videobg.mp4" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>

        </video>
    </div>
    <div class="wrapper">
        <h1>Ошибка 404</h1>
        <p>Наверно вы ошиблись при наборе адреса или ссылка по которой вы пришли, была удалена, перемещена или временно недоступна.</p>
        <p>@Html.ActionLink("Вернуться на сайт","Index","Home")</p>
    </div>
</body>
</html>

PaymentSystem/PaymentSystem/Views/Shared/UserProfilePartial.cshtml
@using Microsoft.AspNet.Identity
<a href="@Url.Action("Details", "Manage")">
    <p class="centered">
        <img src="@Url.Action("GetImage", "Account", new{id = User.Identity.GetUserId()})" class="img-circle" width="60">
    </p>
    <h5 class="centered">@User.Identity.Name</h5>
</a>

PaymentSystem/PaymentSystem/Views/Shared/_AccountsPartial.cshtml
@using Microsoft.AspNet.Identity;
@using PaymentSystem.Util;

@model IEnumerable<DAO.Model.Account>
<div class="col-md-12">
    <h2>Все карты</h2>
    @Html.CreateBootstrapTable(Url.Action("Accounts", new { Controller = "Json", id = ViewContext.RouteData.Values["id"] }),
    new List<ColumnItem>
    {
        new ColumnItem("Name", Html.DisplayNameFor(model => model.Card.Name)),
        new ColumnItem("Balance", Html.DisplayNameFor(model => model.Balance)),
        new ColumnItem("CreationDate", Html.DisplayNameFor(model => model.CreationDate)),
    }, Url.Action("Details", "Card"), "accountIsBlocked")
</div>

PaymentSystem/PaymentSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/others")
    @Scripts.Render("~/bundles/chart")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <section id="container">
        <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Скрыть/Раскрыть меню"></div>
            </div>
            <!--logo start-->
            @Html.ActionLink("ПЛАТЕЖИ ОНЛАЙН", "Index", new { Controller = "Home", area = "" }, new { @class = "logo" })
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!-- notification start -->
                <ul class="nav top-menu">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.Action("Last", "Request")
                    }
                </ul>
                <!-- notification end -->
            </div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li>
                        @using (Html.BeginForm("LogOff", "Account", new { area = "" }))
                        {
                            @Html.AntiForgeryToken()
                            <input type="submit" class="logout" value="Выйти" />
                        }
                    </li>
                </ul>
            </div>
        </header>
        <!--header end-->
        @Html.Action("Index", "Menu")
        <!-- **********************************************************************************************************************************************************
            MAIN CONTENT
            *********************************************************************************************************************************************************** -->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1 main-chart">
                        @RenderBody()
                    </div><!-- /col-lg-9 END SECTION MIDDLE -->
                </div><!--/row -->
            </section>
        </section>
        <!--main content end-->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                &copy; @DateTime.Now.Year — Power by Zadorozhnii
                <a class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/additionScripts")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            if ('@TempData.ContainsKey("SuccessMessage")' == 'True') {
                swal('@TempData["SuccessMessage"]', "", "success");
            }
            var url = '/@ViewContext.RouteData.Values["controller"]/@ViewContext.RouteData.Values["action"]';
            var res = url.replace(/Home/, '').replace(/\/Index/, '');
            var selected = $('#sidebar a[href$="' + res + '"]');
            if (!selected.parent().hasClass('mt')) {
                selected = selected.parent();
                selected.parent().css('display', 'block');
                selected = selected.add(selected.parent().prev());
            }
            selected.addClass('active');
        });
    </script>
    <script src="~/Scripts/Custom.js"></script>
</body>
</html>

PaymentSystem/PaymentSystem/Views/Shared/_LoginLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/backstretch")

    @Scripts.Render("~/bundles/form")

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->

    @RenderBody()
    <script>
        $.backstretch("@Url.Content("~/img/login-bg.jpg")", { speed: 500 });
    </script>
</body>
</html>

PaymentSystem/PaymentSystem/Views/Shared/_OperationsPartial.cshtml
@using PaymentSystem.Util
@model IEnumerable<DAO.Model.Operation>
<div class="col-md-12">
    <h2>Операции</h2>
    @Html.CreateBootstrapTable(Url.Action("Operations", new { Controller = "Json", id = ViewBag.AccountId }),
    new List<ColumnItem>
    {
        new ColumnItem("OperationDate", Html.DisplayNameFor(model => model.OperationDate)),
        new ColumnItem("Amount", Html.DisplayNameFor(model => model.Amount)),
        new ColumnItem("Type", Html.DisplayNameFor(model => model.Type)),
    }, Url.Action("Details", "Operation"))
</div>