PaymentSystem/PaymentSystem/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using BLL.Services;
using DAO.Model;
using DAO.Repository;
using Microsoft.AspNet.Identity;

namespace PaymentSystem.Controllers
{
    public class CardController : Controller
    {
        private readonly IRepositoryFactory _factory;

        public CardController(IRepositoryFactory factory)
        {
            _factory = factory;
        }

        // GET: Card
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Card card)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CardService.CreateCard(card, User.Identity.GetUserId(), _factory);
                    TempData["SuccessMessage"] = "Карта успешно добавлена";
                    return RedirectToAction("Index", "Home");
                }
                catch (ValidationException e)
                {
                    ModelState.AddModelError(e.Property,e.Message);
                }
            }
            return View(card);
        }

        public ActionResult Details(long id = 0)
        {
            var account = AccountService.GetAccount(_factory, id, User.Identity.GetUserId(), User.IsInRole("User"));
            if(account==null)
                return new HttpNotFoundResult();
            return View(account);
        }

        public ActionResult BlockedAccounts()
        {
            return View();
        }

        public ActionResult Block(long id = 0)
        {
            try
            {
                AccountService.BlockAccount(_factory, id, User.Identity.GetUserId(), User.IsInRole("User"));
                return Content("Счет успешно заблокирован");
            }
            catch (ValidationException e)
            {
                return new HttpNotFoundResult(e.Message);
            }
            
        }

        public ActionResult RequertToUnBlock(long id = 0)
        {
            try
            {
                RequestService.AddRequest(id, User.Identity.GetUserId(), _factory);
                return Content("Запрос отправлен администратору на разблокировку.");
            }
            catch (ValidationException e)
            {
                return new HttpNotFoundResult(e.Message);
            }
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UnBlock(long id = 0)
        {
            AccountService.UnBlockAccount(_factory, id);
            return Content("Аккаунт разблокирован.");
        }
    }
}

PaymentSystem/PaymentSystem/Views/Card/BlockedAccounts.cshtml
@using PaymentSystem.Util
@model DAO.Model.Account

@{
    ViewBag.Title = "Заблокированные счета";
}

<div class="col-md-12">
    <h2>@ViewBag.Title</h2>
    @Html.CreateBootstrapTable(Url.Action("BlockedAccounts", new { Controller = "Json"}),
    new List<ColumnItem>
    {
        new ColumnItem("FIO","ФИО"),
        new ColumnItem("Name", Html.DisplayNameFor(model => model.Card.Name)),
        new ColumnItem("Balance", Html.DisplayNameFor(model => model.Balance)),
        new ColumnItem("CreationDate", Html.DisplayNameFor(model => model.CreationDate)),
    }, Url.Action("Details", "Card"))
</div>

PaymentSystem/PaymentSystem/Views/Card/Create.cshtml
@model DAO.Model.Card

@{
    ViewBag.Title = "Новая карта";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Card", FormMethod.Post, new { @class = "card-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-offset-2 col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control", } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-offset-2 col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-offset-2 col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cvc, htmlAttributes: new { @class = "control-label col-md-offset-2 col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Cvc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cvc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-offset-2 col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group card-wrapper">
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                <input type="submit" value="Создать" class="btn btn-default btn-block btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.card.js"></script>
    <script>
        $(document).ready(function () {
            $('form.card-form').card({
                container: '.card-wrapper',
                formSelectors: {
                    numberInput: 'input[name="Number"]',
                    expiryInput: 'input[name="ExpirationDate"]',
                    cvcInput: 'input[name="Cvc"]',
                    nameInput: 'input[name="FullName"]'
                },

                placeholders: {
                    number: '**** **** **** ****',
                    name: 'Иван Иванов',
                    expiry: '**/****',
                    cvc: '***'
                }
            });
        });
    </script>
}

PaymentSystem/PaymentSystem/Views/Card/Details.cshtml
@model DAO.Model.Account

@{
    ViewBag.Title = "Информация о карте";
    ViewBag.AccountId = Model.AccountId;
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance) грн.
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Card.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Card.Name)
        </dd>
    </dl>
        @{
            string text, style, href;
        }
        @if (Model.IsBlocked)
        {
            text = User.IsInRole("Admin") ? "Разблокировать" : "Отправить запрос на разблокировку";
            style = "btn-success";
            href = Url.Action(User.IsInRole("Admin") ? "UnBlock" : "RequertToUnBlock", new { Controller = "Card", id = Model.AccountId });
        }
        else
        {
            text = "Заблокировать";
            style = "btn-danger";
            href = Url.Action("Block", new { Controller = "Card", id = Model.AccountId });
        }
        <br />
        <button class="btn btn-block btn-default @style" href="@href" id="blockAccount">
            @text
        </button>
    @Html.Partial("_OperationsPartial", Model.Operations)
</div>

PaymentSystem/PaymentSystem/Views/Card/Index.cshtml
@{
    ViewBag.Title = "Все карты";
}

@Html.Partial("_AccountsPartial", Enumerable.Empty<DAO.Model.Account>())